### ISSUE TITLE
All-zero matrix when calculating IBP loss

### ISSUE THREAD

**Issue by Yuzz1020** [McGill-NLP/polytropon#5]
Hi, 

Thank you for sharing this awesome project! I have a problem when calculating the IBP loss with your code below.

```
  def neg_log_IBP(self, matrix, alpha=3.):
          matrix = torch.sigmoid(matrix)
          matrix_hard = (matrix > .5).float()
          matrix = matrix_hard - matrix.detach() + matrix
  
          N, _ = matrix.shape
          m = matrix.sum(dim=0)
          m = m[m.nonzero()].squeeze()
          K = len(m)
          def log_factorial(value):
              return torch.lgamma(value + 1)
          logp = 0.
          logp += K * math.log(alpha)
  
          for n in range(N):
              new_features = torch.clamp(matrix[n] - matrix.sum(0), min=0., max=1.).sum()
              logp -= log_factorial(new_features)
  
          logp -= alpha * sum([float(1) / i for i in range(1, N + 1)])
          logp += (log_factorial(N - m) + log_factorial(m - 1)).sum()
          logp -= special.gammaln(N + 1) * K
          return - logp
```

It seems after the thresholding, the resulting ` m[m.nonzero()].squeeze()` usually be an all-zero matrix. I have to manually set the value to `torch.tensor(0.0)` when all-zero matrix appears. I'm wondering have you observe similar behavior in your experiment or did I do something wrong with initialization? Will this affect the final trained skilled module performance?

Thank you!

**Comment by ari9dam** [comment]
+1 

Hi @Yuzz1020, I have similar questions as well.  did you figure out the reason the answers to your questions? Thanks!

**Comment by puraminy** [comment]
I have similar issue for len(m)

```
Traceback (most recent call last):
  File "/home/pouramini/polytropon/src/polytropon/polytropon.py", line 124, in <module>
    logger.warning("forward %s: %s", skilled_variant, skilled_model.forward(task_ids, labels=inputs["input_ids"], add_prior=True, **inputs))
  File "/home/pouramini/polytropon/src/polytropon/polytropon.py", line 78, in forward
    aux_loss = [self.neg_log_IBP(p) for n, p in self.model.named_parameters() if "skill_logits" in n]
  File "/home/pouramini/polytropon/src/polytropon/polytropon.py", line 78, in <listcomp>
    aux_loss = [self.neg_log_IBP(p) for n, p in self.model.named_parameters() if "skill_logits" in n]
  File "/home/pouramini/polytropon/src/polytropon/polytropon.py", line 94, in neg_log_IBP
    K = len(m)
  File "/home/pouramini/anaconda3/lib/python3.9/site-packages/torch/_tensor.py", line 705, in __len__
    raise TypeError("len() of a 0-d tensor")
TypeError: len() of a 0-d tensor
```

**Comment by ducdauge** [comment]
Hi all! I pushed a new version of neg_log_IBP which hopefully should be more robust. A few notes:
- having a full-zero matrix is weird, because the auxiliary loss discourages that. There are two differentiable terms, the first one encourages the columns of Z to be unique (so a full-zero matrix is penalised).
- @puraminy which version of Pytorch are you using? In my version, the length of an empty (0-d) tensor is 0, so it should not throw an error.

**Comment by puraminy** [comment]
Thank you for your attention, I use:

```
torch==1.12.0
torchaudio==0.12.0
torchvision==0.13.0
```

I tried to put it in `try` block:

```
      try:
            K = len(m)
        except:
            K = 0
```

**Comment by ducdauge** [comment]
I have
`torch==1.12.1
`
and cannot replicate your error.

```
>>> len(torch.Tensor([]))
0
```

**Comment by puraminy** [comment]
By using your latest code, the problem was resolved, and currently I can't reproduce it ... Also, I used my local t5-base (Maybe it had a role).

I'm reading your paper to understand what your code does. Because I had a similar idea for generation or seq2seq using T5. However, I currently don't know what your example code (at the end of file does). I decoded the generated token ids, and they are part of the same inputs.

I will read more, but you may explain the example or guide me in future how can I use your code for multi-task seq2seq with T5
